.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. neom_qt test_neom_qt
clean: FORCE
	$(MAKE) -C .. neom_qt_clean test_neom_qt_clean
check: FORCE
	$(MAKE) -C .. test_neom_qt_check
neom-qt neom-qt.exe: FORCE
	 $(MAKE) -C .. neom_qt
